Страница обменов пользователя
lizitca/booksharing-frontend pull request #19
Opened 2017-06-20 15:01 UTC by aisel01

2017-06-20 18:35 UTC, dustyo-O commented
тебе нужно поребейзить веточку по master и порешать конфликты. пиши, если будут трудности)

2017-06-20 18:43 UTC, dustyo-O approved these changes
выпилить js комменты, отребейзить по мастеру (git rebase master) и влить. После того как ты отребейзишь - ветка будет отказываться вливаться - надо сделать git push --force

2017-06-20 18:43 UTC, dustyo-O commented on exchanges.html
> +		//newExchange.querySelector('.origin-user-name').innerText = exchange.origin_user.name;
все, что не пригодилось - выпиливаем

2017-06-20 18:43 UTC, dustyo-O commented on exchanges.html
> +			url: '/booksharing-backend/api/exchange.update.php',
оно ведь так не работает? надо прибавлять адрес бекэнда к началу строки - или я что-то упускаю?

Надо бы побыстрее решить с файлом настройки, из #18 , пока у нас не стало неконтролируемо много таких мест

2017-06-20 18:43 UTC, dustyo-O commented on exchanges.html
> +			url: '/booksharing-backend/api/exchange.update.php',
Но в этом PR можно не править, а оставить как есть

2017-06-20 18:47 UTC, aisel01 commented on exchanges.html
> +			url: '/booksharing-backend/api/exchange.update.php',
да,нужно заменить /booksharing-backend на адрес бекэнда

2017-06-24 12:50 UTC, dustyo-O commented
что там с тем, чтобы отребейзить и влить?

2017-06-24 14:41 UTC, aisel01 commented
Пробую, но после git rebase master  мои изменения пропадают

2017-06-24 14:50 UTC, dustyo-O commented
Там происходит конфликт, мы такое разбирали. Поправь style.css, сделай git add . И git rebase --continue

2017-06-24 17:22 UTC, dustyo-O requested changes
надо удалить артефакты от конфликта

2017-06-24 17:22 UTC, dustyo-O commented on css/style.css
> +<<<<<<< HEAD
приехало от конфликтов :)

2017-06-24 18:36 UTC, dustyo-O approved these changes

2017-06-24 18:36 UTC, dustyo-O commented
ok - можно вливать

2017-06-24 18:37 UTC, merged