Добавлены книги пользователя в профиле
lizitca/booksharing-frontend pull request #20
Opened 2017-06-24 12:12 UTC by slotovi4

2017-06-24 12:57 UTC, dustyo-O requested changes
почисти от ненужного и пару замечаний

2017-06-24 12:57 UTC, dustyo-O commented on back/functions.php
> +<?php
бекэнд надо выпилить

2017-06-24 12:57 UTC, dustyo-O commented on css/style.css
> -.current
по-моему, ты выпиливаешь нужные стили тут

2017-06-24 12:57 UTC, dustyo-O commented on jquery/.bower.json
> +{
этой папки тут быть не должно

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +											<h2 class="userName">Scarlett Johansson</h2>
давай делать user-name вместо camelCase

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +													<li><i class="fa-li fa fa-book"></i>Всего книг: <span class="booksValue">456</span></li>
и тут тоже - везде нейминг в css делать через kebab-case

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +                                        <a href="javascript:" class="btn btn-success pull-right">Еще книги</a>
зачем javascript: ? если для того, чтобы исключить прокрутку - то мы это делаем через preventDefault на онклике

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +	<style>
стили в файлы стилей лучше

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +	<script type="text/javascript">
пустой script - надо выпилить

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +	<script>
что-то отступы подозрительные

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +                    console.log(responce);
console.log из готового лучше выпиливать

2017-06-24 12:57 UTC, dustyo-O commented on profile.html
> +                function () {console.log("ошибка!");
поставь задачу в issues на более качественные сообщения об ошибках

2017-06-24 13:05 UTC, slotovi4 commented on css/style.css
> -.current
css я не трогал

2017-06-24 13:16 UTC, dustyo-O commented on css/style.css
> -.current
Система контроля контроля версий так не считает:) тут собраны изменения, которые применятся, если влить ПР. Надо в твоей ветке привести CSS к тому виду, в котором он в репозитории. Можно просто пойти по ссылке Code и скопировать из файла

2017-06-24 13:16 UTC, dustyo-O commented on css/style.css
> -.current
Система контроля контроля версий так не считает:) тут собраны изменения, которые применятся, если влить ПР. Надо в твоей ветке привести CSS к тому виду, в котором он в репозитории. Можно просто пойти по ссылке Code и скопировать из файла

2017-06-27 23:46 UTC, dustyo-O commented
так-с, ну я почистил, вливаю

2017-06-27 23:46 UTC, merged